ALTER TABLE stores ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN spice_required INTEGER NOT NULL DEFAULT 0;
ALTER TABLE meal_menu_items ADD COLUMN spice_required INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN spice_level TEXT NOT NULL DEFAULT '';
