const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const randomToken=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
async function digest(value){const bytes=new TextEncoder().encode(value);return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(request){try{return await request.json()}catch{return{}}}
function bearer(request){const h=request.headers.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7):''}
async function session(env,request,role){const token=bearer(request);if(!token)return null;const hash=await digest(token),row=await env.DB.prepare('SELECT s.*,p.name,p.group_name FROM auth_sessions s LEFT JOIN people p ON p.id=s.person_id WHERE token_hash=? AND expires_at>?').bind(hash,Date.now()).first();if(!row||role&&row.role!==role)return null;return row}
async function log(env,actor,action,type,id='',detail=''){await env.DB.prepare('INSERT INTO logs(created_at,actor,action,target_type,target_id,detail) VALUES(?,?,?,?,?,?)').bind(now(),actor,action,type,id,detail).run()}
async function publicBootstrap(env){
  const people=await env.DB.prepare("SELECT id,name,group_name AS 'group',sort_order FROM people WHERE active=1 ORDER BY sort_order,name").all();
  const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,s.name AS storeName FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date,CASE m.meal_type WHEN '午餐' THEN 0 ELSE 1 END").all();
  return{people:people.results,meals:meals.results};
}
async function userBootstrap(env,personId){
  const person=await env.DB.prepare("SELECT id,name,group_name AS 'group' FROM people WHERE id=? AND active=1").bind(personId).first();
  const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,s.name AS storeName FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date,CASE m.meal_type WHEN '午餐' THEN 0 ELSE 1 END").all();
  const menus=await env.DB.prepare("SELECT mm.id,mm.meal_id AS mealId,mm.name,mm.price,mm.sort_order AS sortOrder,COALESCE(t.qty,0) AS popularity FROM meal_menu_items mm LEFT JOIN (SELECT meal_menu_id,SUM(qty) qty FROM orders WHERE active=1 GROUP BY meal_menu_id)t ON t.meal_menu_id=mm.id WHERE mm.active=1 ORDER BY mm.meal_id,mm.sort_order").all();
  const orders=await env.DB.prepare("SELECT id,meal_id AS mealId,meal_menu_id AS mealMenuId,name,price,qty,note FROM orders WHERE person_id=? AND active=1 ORDER BY updated_at").bind(personId).all();
  return{person,meals:meals.results,menus:menus.results,orders:orders.results};
}
async function saveOrder(env,s,data){
  const meal=await env.DB.prepare("SELECT m.*,e.id event_id FROM meals m JOIN events e ON e.id=m.event_id WHERE m.id=? AND m.active=1 AND e.active=1").bind(data.mealId).first();
  if(!meal)return json({ok:false,message:'找不到餐次'},404);
  if(meal.status!=='登記中')return json({ok:false,message:'本餐已停止登記'},409);
  const chosen=(Array.isArray(data.items)?data.items:[]).filter(x=>Number(x.qty)>0&&Number(x.qty)<=20);
  const allowed=await env.DB.prepare('SELECT id,name,price FROM meal_menu_items WHERE meal_id=? AND active=1').bind(meal.id).all(),map=new Map(allowed.results.map(x=>[x.id,x]));
  if(chosen.some(x=>!map.has(x.id)))return json({ok:false,message:'餐點資料已更新，請重新整理'},409);
  await env.DB.prepare('UPDATE orders SET active=0,updated_at=? WHERE meal_id=? AND person_id=? AND active=1').bind(now(),meal.id,s.person_id).run();
  for(const item of chosen){const m=map.get(item.id);await env.DB.prepare('INSERT INTO orders(id,meal_id,event_id,person_id,meal_menu_id,name,price,qty,note,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?)').bind(crypto.randomUUID(),meal.id,meal.event_id,s.person_id,m.id,m.name,m.price,Number(item.qty),String(data.note||'').slice(0,200),now()).run()}
  await env.DB.prepare("INSERT INTO meal_people(meal_id,person_id,status,picked) VALUES(?,?,'已訂',0) ON CONFLICT(meal_id,person_id) DO UPDATE SET status='已訂',picked=0,picked_at=NULL").bind(meal.id,s.person_id).run();
  await log(env,s.name||s.person_id,'SAVE_ORDER','meal',meal.id,`共${chosen.reduce((a,x)=>a+Number(x.qty),0)}份`);
  return json({ok:true});
}
async function runBatch(env,statements,size=80){for(let i=0;i<statements.length;i+=size)await env.DB.batch(statements.slice(i,i+size))}
async function importLegacy(env,payload,actor){
  const src=payload?.kind==='meal-duty-diagnostic-backup'?payload.state:payload;
  if(!src||!Array.isArray(src.people)||!Array.isArray(src.events)||!Array.isArray(src.orders))throw new Error('不是有效的NAS診斷JSON');
  const people=[...(src.people||[])],stores=[...(src.stores||[])],events=[...(src.events||[])],meals=[...(src.meals||[])];
  const peopleIds=new Set(people.map(x=>x.id)),storeIds=new Set(stores.map(x=>x.id)),eventIds=new Set(events.map(x=>x.id)),mealIds=new Set(meals.map(x=>x.id));
  const addPerson=id=>{if(id&&!peopleIds.has(id)){peopleIds.add(id);people.push({id,name:`保留人員（${id}）`,group:'其他',active:false})}};
  const addStore=id=>{if(id&&!storeIds.has(id)){storeIds.add(id);stores.push({id,name:`保留店家（${id}）`,active:false})}};
  const addEvent=(id,date='2000-01-01')=>{if(id&&!eventIds.has(id)){eventIds.add(id);events.push({id,name:`保留活動（${id}）`,start:date,end:date,status:'已結束',active:false})}};
  const addMeal=(id,eventId,date='2000-01-01')=>{if(id&&!mealIds.has(id)){const eid=eventId||`legacy-event-${id}`;addEvent(eid,date);mealIds.add(id);meals.push({id,eventId:eid,date,type:'舊餐次',status:'停止登記',active:false})}};
  for(const x of src.menu||[])addStore(x.storeId);
  for(const x of src.mealMenus||[]){addMeal(x.mealId,null);addStore(x.storeId)}
  for(const x of meals){addEvent(x.eventId,x.date);addStore(x.storeId)}
  for(const x of src.orders||[]){addPerson(x.personId);addEvent(x.eventId);addMeal(x.mealId,x.eventId)}
  for(const x of src.mealPeople||[]){addPerson(x.personId);addMeal(x.mealId,null)}
  for(const x of src.payments||[]){addPerson(x.personId);addEvent(x.eventId)}
  let stage='準備匯入';
  try{
    stage='人員';await runBatch(env,people.map(p=>env.DB.prepare("INSERT INTO people(id,name,group_name,sort_order,active) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,group_name=excluded.group_name,sort_order=excluded.sort_order,active=excluded.active").bind(p.id,p.name,p.group||'其他',p.sort||0,p.active===false?0:1)));
    stage='店家';await runBatch(env,stores.map(s=>env.DB.prepare("INSERT INTO stores(id,name,sort_order,active) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,sort_order=excluded.sort_order,active=excluded.active").bind(s.id,s.name,s.sort||0,s.active===false?0:1)));
    stage='店家菜單';await runBatch(env,(src.menu||[]).map(x=>env.DB.prepare("INSERT INTO menu_items(id,store_id,name,price,sort_order,active) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET store_id=excluded.store_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order,active=excluded.active").bind(x.id,x.storeId,x.name,x.price||0,x.sort||0,x.active===false?0:1)));
    stage='活動';await runBatch(env,events.map(e=>env.DB.prepare("INSERT INTO events(id,name,start_date,end_date,status,active) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,start_date=excluded.start_date,end_date=excluded.end_date,status=excluded.status,active=excluded.active").bind(e.id,e.name,e.start||'2000-01-01',e.end||e.start||'2000-01-01',e.status||'進行中',e.active===false?0:1)));
    stage='餐次';await runBatch(env,meals.map(m=>env.DB.prepare("INSERT INTO meals(id,event_id,meal_date,meal_type,store_id,status,active) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET event_id=excluded.event_id,meal_date=excluded.meal_date,meal_type=excluded.meal_type,store_id=excluded.store_id,status=excluded.status,active=excluded.active").bind(m.id,m.eventId,m.date||'2000-01-01',m.type||'舊餐次',m.storeId||null,m.status||'登記中',m.active===false?0:1)));
    stage='餐次菜單';await runBatch(env,(src.mealMenus||[]).map(x=>env.DB.prepare("INSERT INTO meal_menu_items(id,meal_id,source_id,store_id,name,price,special,sort_order,active) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET meal_id=excluded.meal_id,source_id=excluded.source_id,store_id=excluded.store_id,name=excluded.name,price=excluded.price,special=excluded.special,sort_order=excluded.sort_order,active=excluded.active").bind(x.id,x.mealId,x.sourceId||null,x.storeId||null,x.name,x.price||0,x.special?1:0,x.sort||0,x.active===false?0:1)));
    stage='訂單';await runBatch(env,(src.orders||[]).map(o=>env.DB.prepare("INSERT INTO orders(id,meal_id,event_id,person_id,meal_menu_id,name,price,qty,note,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET meal_id=excluded.meal_id,event_id=excluded.event_id,person_id=excluded.person_id,meal_menu_id=excluded.meal_menu_id,name=excluded.name,price=excluded.price,qty=excluded.qty,note=excluded.note,active=excluded.active,updated_at=excluded.updated_at").bind(o.id,o.mealId,o.eventId,o.personId,o.mealMenuId,o.name,o.price||0,o.qty||1,o.note||'',o.active===false?0:1,o.updatedAt||now())));
    stage='領餐狀態';await runBatch(env,(src.mealPeople||[]).map(x=>env.DB.prepare("INSERT INTO meal_people(meal_id,person_id,status,picked,picked_at) VALUES(?,?,?,?,?) ON CONFLICT(meal_id,person_id) DO UPDATE SET status=excluded.status,picked=excluded.picked,picked_at=excluded.picked_at").bind(x.mealId,x.personId,x.status||'已訂',x.picked?1:0,x.pickedAt||null)));
    stage='收費狀態';await runBatch(env,(src.payments||[]).map(x=>env.DB.prepare("INSERT INTO payments(event_id,person_id,paid,paid_at) VALUES(?,?,?,?) ON CONFLICT(event_id,person_id) DO UPDATE SET paid=excluded.paid,paid_at=excluded.paid_at").bind(x.eventId,x.personId,x.paid?1:0,x.paidAt||null)));
  }catch(error){throw new Error(`匯入「${stage}」時失敗：${error.message}`)}
  await log(env,actor,'IMPORT_LEGACY','system','',`${src.people.length}人｜${(src.stores||[]).length}店｜${src.events.length}活動｜${src.orders.length}訂單`);
  return{people:src.people.length,stores:(src.stores||[]).length,events:src.events.length,meals:(src.meals||[]).length,orders:src.orders.length};
}
export async function onRequest({request,env,params}){
  const segments=Array.isArray(params.path)?params.path:[params.path].filter(Boolean),path='/'+segments.join('/'),method=request.method;
  try{
    if(path==='/health')return json({ok:true,service:'meal-duty-cloudflare',version:'0.1.0'});
    if(path==='/public/bootstrap'&&method==='GET')return json({ok:true,...await publicBootstrap(env)});
    if(path==='/auth/person'&&method==='POST'){
      const d=await body(request),person=await env.DB.prepare('SELECT * FROM people WHERE id=? AND active=1').bind(d.personId).first();
      if(!person||!person.employee_code_hash||person.employee_code_hash!==await digest(String(d.code||'')))return json({ok:false,message:'姓名或五碼工號不正確'},401);
      const token=randomToken(),expires=Date.now()+30*24*3600*1000;await env.DB.prepare("INSERT INTO auth_sessions(token_hash,person_id,role,expires_at,code_version) VALUES(?,?,'person',?,?)").bind(await digest(token),person.id,expires,person.code_version).run();await log(env,person.name,'LOGIN','person',person.id,'登入成功');return json({ok:true,token,person:{id:person.id,name:person.name,group:person.group_name}});
    }
    if(path==='/auth/admin'&&method==='POST'){
      const d=await body(request),stored=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(!stored||stored.value!==await digest(String(d.password||'')))return json({ok:false,message:stored?'管理密碼不正確':'尚未設定管理密碼'},401);const token=randomToken();await env.DB.prepare("INSERT INTO auth_sessions(token_hash,role,expires_at) VALUES(?,'admin',?)").bind(await digest(token),Date.now()+8*3600*1000).run();return json({ok:true,token});
    }
    if(path==='/me'&&method==='GET'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);return json({ok:true,...await userBootstrap(env,s.person_id)});}
    if(path==='/orders'&&method==='POST'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);return saveOrder(env,s,await body(request));}
    if(path==='/admin/procurement'&&method==='GET'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,COALESCE(s.name,'尚未指定店家') AS storeName FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date DESC,CASE m.meal_type WHEN '晚餐' THEN 0 ELSE 1 END").all();const items=await env.DB.prepare("SELECT o.meal_id AS mealId,COALESCE(item_store.name,meal_store.name,'其他加購') AS storeName,o.name,SUM(o.qty) AS qty,SUM(o.price*o.qty) AS total FROM orders o JOIN meals m ON m.id=o.meal_id LEFT JOIN meal_menu_items mm ON mm.id=o.meal_menu_id LEFT JOIN stores item_store ON item_store.id=mm.store_id LEFT JOIN stores meal_store ON meal_store.id=m.store_id WHERE o.active=1 GROUP BY o.meal_id,COALESCE(item_store.name,meal_store.name,'其他加購'),o.name ORDER BY o.meal_id,storeName,o.name").all();return json({ok:true,meals:meals.results,items:items.results});}
    if(path==='/admin/bootstrap'&&method==='GET'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const counts={};for(const t of ['people','stores','events','meals','orders','logs'])counts[t]=(await env.DB.prepare(`SELECT COUNT(*) n FROM ${t}`).first()).n;const [people,stores,menu,events,meals]=await Promise.all([env.DB.prepare("SELECT id,name,group_name AS 'group',sort_order AS sortOrder,CASE WHEN employee_code_hash IS NULL THEN 0 ELSE 1 END AS hasCode FROM people WHERE active=1 ORDER BY sort_order,name").all(),env.DB.prepare("SELECT id,name,sort_order AS sortOrder FROM stores WHERE active=1 ORDER BY sort_order,name").all(),env.DB.prepare("SELECT id,store_id AS storeId,name,price,sort_order AS sortOrder FROM menu_items WHERE active=1 ORDER BY store_id,sort_order,name").all(),env.DB.prepare("SELECT id,name,start_date AS startDate,end_date AS endDate,status FROM events WHERE active=1 ORDER BY start_date DESC").all(),env.DB.prepare("SELECT m.id,m.event_id AS eventId,m.meal_date AS date,m.meal_type AS type,m.store_id AS storeId,m.status,COUNT(mm.id) AS menuCount FROM meals m LEFT JOIN meal_menu_items mm ON mm.meal_id=m.id AND mm.active=1 WHERE m.active=1 GROUP BY m.id ORDER BY m.meal_date,CASE m.meal_type WHEN '午餐' THEN 0 ELSE 1 END").all()]);return json({ok:true,counts,people:people.results,stores:stores.results,menu:menu.results,events:events.results,meals:meals.results});}
    if(path==='/admin/setup'&&method==='POST'){const existing=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(existing)return json({ok:false,message:'管理密碼已設定'},409);const d=await body(request);if(String(d.password||'').length<6)return json({ok:false,message:'管理密碼至少6碼'},400);await env.DB.prepare("INSERT INTO settings(key,value) VALUES('admin_password_hash',?)").bind(await digest(String(d.password))).run();return json({ok:true});}
    if(path==='/admin/import-legacy'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);return json({ok:true,summary:await importLegacy(env,await body(request),'管理者')});}
    if(path==='/admin/import-stores'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),incoming=Array.isArray(d.stores)?d.stores:[];if(!incoming.length)return json({ok:false,message:'檔案內沒有店家資料'},400);const [oldStores,oldMenu]=await Promise.all([env.DB.prepare('SELECT id,name FROM stores').all(),env.DB.prepare('SELECT id,store_id,name FROM menu_items').all()]),storeMap=new Map(oldStores.results.map(x=>[x.name.trim(),x])),menuMap=new Map(oldMenu.results.map(x=>[`${x.store_id}\n${x.name.trim()}`,x]));let storeCount=0,itemCount=0,sortStore=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0) n FROM stores').first()).n;const statements=[];for(const raw of incoming){const name=String(raw.name||'').trim();if(!name)continue;let store=storeMap.get(name);if(!store){store={id:crypto.randomUUID(),name};storeMap.set(name,store);statements.push(env.DB.prepare('INSERT INTO stores(id,name,sort_order,active) VALUES(?,?,?,1)').bind(store.id,name,++sortStore))}else statements.push(env.DB.prepare('UPDATE stores SET active=1 WHERE id=?').bind(store.id));storeCount++;let sortItem=0;for(const rawItem of(Array.isArray(raw.menu)?raw.menu:[])){const itemName=String(rawItem.name||'').trim();if(!itemName)continue;const price=Math.max(0,Math.round(Number(rawItem.price)||0)),key=`${store.id}\n${itemName}`,old=menuMap.get(key);if(old)statements.push(env.DB.prepare('UPDATE menu_items SET price=?,active=1 WHERE id=?').bind(price,old.id));else statements.push(env.DB.prepare('INSERT INTO menu_items(id,store_id,name,price,sort_order,active) VALUES(?,?,?,?,?,1)').bind(crypto.randomUUID(),store.id,itemName,price,++sortItem));itemCount++}}await runBatch(env,statements);await log(env,'管理者','IMPORT_STORES','system','',`${storeCount}店｜${itemCount}項`);return json({ok:true,stores:storeCount,items:itemCount});}
    if(path==='/admin/person-code'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),code=String(d.code||'');if(!/^\d{5}$/.test(code))return json({ok:false,message:'工號必須是五位數'},400);await env.DB.prepare('UPDATE people SET employee_code_hash=?,code_version=code_version+1 WHERE id=?').bind(await digest(code),d.personId).run();await env.DB.prepare("DELETE FROM auth_sessions WHERE person_id=? AND role='person'").bind(d.personId).run();return json({ok:true});}
    if(path==='/admin/people'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),group=['師級','常日','輪班','其他'].includes(d.group)?d.group:'其他';if(!name)return json({ok:false,message:'請輸入姓名'},400);const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM people').first()).n;await env.DB.prepare('INSERT INTO people(id,name,group_name,sort_order,active) VALUES(?,?,?,?,1)').bind(id,name,group,sort).run();await log(env,'管理者','ADD_PERSON','person',id,`${name}｜${group}`);return json({ok:true,id});}
    if(path==='/admin/person-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request);await env.DB.prepare('UPDATE people SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();await log(env,'管理者',d.active?'RESTORE_PERSON':'DISABLE_PERSON','person',d.id,'');return json({ok:true});}
    if(path==='/admin/stores'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim();if(!name)return json({ok:false,message:'請輸入店家名稱'},400);if(d.id){await env.DB.prepare('UPDATE stores SET name=? WHERE id=?').bind(name,d.id).run();await log(env,'管理者','UPDATE_STORE','store',d.id,name);return json({ok:true,id:d.id})}const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM stores').first()).n;await env.DB.prepare('INSERT INTO stores(id,name,sort_order,active) VALUES(?,?,?,1)').bind(id,name,sort).run();await log(env,'管理者','ADD_STORE','store',id,name);return json({ok:true,id});}
    if(path==='/admin/store-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request);await env.DB.prepare('UPDATE stores SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();await log(env,'管理者',d.active?'RESTORE_STORE':'DISABLE_STORE','store',d.id,'');return json({ok:true});}
    if(path==='/admin/menu-items'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),price=Math.max(0,Math.round(Number(d.price)||0));if(!name||!d.storeId)return json({ok:false,message:'店家與餐點名稱不可空白'},400);if(d.id){await env.DB.prepare('UPDATE menu_items SET name=?,price=? WHERE id=? AND store_id=?').bind(name,price,d.id,d.storeId).run();await log(env,'管理者','UPDATE_MENU','menu',d.id,`${name}｜${price}`);return json({ok:true,id:d.id})}const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM menu_items WHERE store_id=?').bind(d.storeId).first()).n;await env.DB.prepare('INSERT INTO menu_items(id,store_id,name,price,sort_order,active) VALUES(?,?,?,?,?,1)').bind(id,d.storeId,name,price,sort).run();await log(env,'管理者','ADD_MENU','menu',id,`${name}｜${price}`);return json({ok:true,id});}
    if(path==='/admin/menu-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request);await env.DB.prepare('UPDATE menu_items SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();await log(env,'管理者',d.active?'RESTORE_MENU':'DISABLE_MENU','menu',d.id,'');return json({ok:true});}
    if(path==='/admin/events'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),start=String(d.startDate||''),end=String(d.endDate||''),startDate=new Date(`${start}T00:00:00Z`),endDate=new Date(`${end}T00:00:00Z`),days=Math.round((endDate-startDate)/86400000)+1;if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||days<1||days>4)return json({ok:false,message:'請輸入活動名稱，日期需為1～4天'},400);const eventId=crypto.randomUUID(),statements=[env.DB.prepare("INSERT INTO events(id,name,start_date,end_date,status,active) VALUES(?,?,?,?, '進行中',1)").bind(eventId,name,start,end)];for(let i=0;i<days;i++){const date=new Date(startDate.getTime()+i*86400000).toISOString().slice(0,10);for(const type of ['午餐','晚餐'])statements.push(env.DB.prepare("INSERT INTO meals(id,event_id,meal_date,meal_type,status,active) VALUES(?,?,?,?, '停止登記',1)").bind(crypto.randomUUID(),eventId,date,type))}await env.DB.batch(statements);await log(env,'管理者','ADD_EVENT','event',eventId,`${name}｜${start}～${end}`);return json({ok:true,id:eventId,meals:days*2});}
    if(path==='/admin/meal-status'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),status=d.status==='登記中'?'登記中':'停止登記';await env.DB.prepare('UPDATE meals SET status=? WHERE id=? AND active=1').bind(status,d.mealId).run();await log(env,'管理者','MEAL_STATUS','meal',d.mealId,status);return json({ok:true,status});}
    if(path==='/admin/meal-store'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),meal=await env.DB.prepare('SELECT id FROM meals WHERE id=? AND active=1').bind(d.mealId).first(),store=await env.DB.prepare('SELECT id,name FROM stores WHERE id=? AND active=1').bind(d.storeId).first();if(!meal||!store)return json({ok:false,message:'找不到餐次或店家'},404);const source=await env.DB.prepare('SELECT id,name,price,sort_order FROM menu_items WHERE store_id=? AND active=1 ORDER BY sort_order,name').bind(store.id).all();if(!source.results.length)return json({ok:false,message:'這家店尚無可用菜單'},400);if(d.mode!=='append')await env.DB.prepare('UPDATE meal_menu_items SET active=0 WHERE meal_id=?').bind(meal.id).run();await env.DB.prepare('UPDATE meals SET store_id=? WHERE id=?').bind(store.id,meal.id).run();const statements=source.results.map(x=>env.DB.prepare('INSERT INTO meal_menu_items(id,meal_id,source_id,store_id,name,price,special,sort_order,active) VALUES(?,?,?,?,?,?,0,?,1)').bind(crypto.randomUUID(),meal.id,x.id,store.id,x.name,x.price,x.sort_order));await runBatch(env,statements);await log(env,'管理者',d.mode==='append'?'APPEND_MEAL_STORE':'REPLACE_MEAL_STORE','meal',meal.id,store.name);return json({ok:true,items:source.results.length});}
    if(path==='/admin/meal-special'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),price=Math.max(0,Math.round(Number(d.price)||0));if(!name||!d.mealId)return json({ok:false,message:'請輸入品項與價格'},400);const sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM meal_menu_items WHERE meal_id=?').bind(d.mealId).first()).n,id=crypto.randomUUID();await env.DB.prepare('INSERT INTO meal_menu_items(id,meal_id,name,price,special,sort_order,active) VALUES(?,?,?,?,1,?,1)').bind(id,d.mealId,name,price,sort).run();await log(env,'管理者','ADD_MEAL_SPECIAL','meal',d.mealId,`${name}｜${price}`);return json({ok:true,id});}
    return json({ok:false,message:'找不到API'},404);
  }catch(error){return json({ok:false,message:error.message||'伺服器錯誤'},500)}
}
