const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const randomToken=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
async function digest(value){const bytes=new TextEncoder().encode(value);return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(request){try{return await request.json()}catch{return{}}}
function bearer(request){const h=request.headers.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7):''}
async function session(env,request,role){const token=bearer(request);if(!token)return null;const hash=await digest(token),row=await env.DB.prepare('SELECT s.*,p.name,p.group_name,p.active AS person_active FROM auth_sessions s LEFT JOIN people p ON p.id=s.person_id WHERE token_hash=? AND expires_at>?').bind(hash,Date.now()).first();if(!row)return null;if(row.person_id&&!row.person_active)return null;if(role==='admin'&&row.role!=='admin')return null;if(role==='person'&&!row.person_id)return null;return row}
async function adminPersonIds(env){const row=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_person_ids'").first();try{return new Set(JSON.parse(row?.value||'[]'))}catch{return new Set()}}
async function saveAdminPersonIds(env,ids){await env.DB.prepare("INSERT INTO settings(key,value) VALUES('admin_person_ids',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify([...ids])).run()}
async function log(env,actor,action,type,id='',detail=''){await env.DB.prepare('INSERT INTO logs(created_at,actor,action,target_type,target_id,detail) VALUES(?,?,?,?,?,?)').bind(now(),actor,action,type,id,detail).run()}
async function ensurePinAttempts(env){await env.DB.prepare('CREATE TABLE IF NOT EXISTS pin_attempts (attempt_key TEXT PRIMARY KEY, failures INTEGER NOT NULL DEFAULT 0, window_started_at INTEGER NOT NULL, locked_until INTEGER NOT NULL DEFAULT 0)').run()}
async function pinAttemptKey(request,personId){return digest(`${request.headers.get('CF-Connecting-IP')||'unknown'}|${personId}`)}
async function pinAttemptStatus(env,key){await ensurePinAttempts(env);return env.DB.prepare('SELECT failures,window_started_at AS windowStartedAt,locked_until AS lockedUntil FROM pin_attempts WHERE attempt_key=?').bind(key).first()}
async function recordPinFailure(env,key,current){const time=Date.now(),windowMs=10*60*1000,within=current&&time-Number(current.windowStartedAt)<windowMs,failures=within?Number(current.failures)+1:1,windowStartedAt=within?Number(current.windowStartedAt):time,lockedUntil=failures>=5?time+windowMs:0;await env.DB.prepare('INSERT INTO pin_attempts(attempt_key,failures,window_started_at,locked_until) VALUES(?,?,?,?) ON CONFLICT(attempt_key) DO UPDATE SET failures=excluded.failures,window_started_at=excluded.window_started_at,locked_until=excluded.locked_until').bind(key,failures,windowStartedAt,lockedUntil).run();return lockedUntil}
async function publicBootstrap(env){
  const people=await env.DB.prepare("SELECT id,name,group_name AS 'group',sort_order FROM people WHERE active=1 ORDER BY sort_order,name").all();
  const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,s.name AS storeName FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date,CASE m.meal_type WHEN '特餐' THEN 0 WHEN '午餐' THEN 1 WHEN '晚餐' THEN 2 ELSE 3 END").all();
  return{people:people.results,meals:meals.results};
}
async function userBootstrap(env,personId,isAdmin=false){
  const person=await env.DB.prepare("SELECT id,name,group_name AS 'group' FROM people WHERE id=? AND active=1").bind(personId).first();
  const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,s.name AS storeName FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date,CASE m.meal_type WHEN '特餐' THEN 0 WHEN '午餐' THEN 1 WHEN '晚餐' THEN 2 ELSE 3 END").all();
  const menus=await env.DB.prepare("SELECT mm.id,mm.meal_id AS mealId,mm.name,mm.price,mm.spice_required AS spiceRequired,mm.sort_order AS sortOrder,COALESCE(t.qty,0) AS popularity FROM meal_menu_items mm LEFT JOIN (SELECT meal_menu_id,SUM(qty) qty FROM orders WHERE active=1 GROUP BY meal_menu_id)t ON t.meal_menu_id=mm.id WHERE mm.active=1 ORDER BY mm.meal_id,mm.sort_order").all();
  const orders=await env.DB.prepare("SELECT id,meal_id AS mealId,meal_menu_id AS mealMenuId,name,price,qty,spice_level AS spiceLevel,note FROM orders WHERE person_id=? AND active=1 ORDER BY updated_at").bind(personId).all();
  const admins=await adminPersonIds(env);
  return{person:{...person,isAdmin,canClaimAdmin:admins.size===0},meals:meals.results,menus:menus.results,orders:orders.results};
}
async function saveOrder(env,s,data){
  const meal=await env.DB.prepare("SELECT m.*,e.id event_id FROM meals m JOIN events e ON e.id=m.event_id WHERE m.id=? AND m.active=1 AND e.active=1").bind(data.mealId).first();
  if(!meal)return json({ok:false,message:'找不到餐次'},404);
  if(meal.status!=='登記中')return json({ok:false,message:'本餐已停止登記'},409);
  const rawChosen=(Array.isArray(data.items)?data.items:[]).filter(x=>Number(x.qty)>0&&Number(x.qty)<=20),grouped=new Map();
  for(const x of rawChosen){const id=String(x.id||''),spiceLevel=String(x.spiceLevel||''),key=`${id}\u001f${spiceLevel}`,old=grouped.get(key);grouped.set(key,{id,spiceLevel,qty:Number(x.qty)+Number(old?.qty||0)})}
  const chosen=[...grouped.values()],itemTotals=new Map();
  for(const x of chosen){itemTotals.set(x.id,(itemTotals.get(x.id)||0)+x.qty);if(itemTotals.get(x.id)>20)return json({ok:false,message:'同一餐點合計最多20份'},400)}
  const allowed=await env.DB.prepare('SELECT id,name,price,spice_required AS spiceRequired FROM meal_menu_items WHERE meal_id=? AND active=1').bind(meal.id).all(),map=new Map(allowed.results.map(x=>[x.id,x])),spiceLevels=new Set(['不辣','小辣','中辣','大辣']);
  if(chosen.some(x=>!map.has(x.id)))return json({ok:false,message:'餐點資料已更新，請重新整理'},409);
  if(chosen.some(x=>{const m=map.get(x.id),spice=String(x.spiceLevel||'');return m.spiceRequired?!spiceLevels.has(spice):spice!==''}))return json({ok:false,message:'請為需要辣度的餐點選擇不辣、小辣、中辣或大辣'},400);
  await env.DB.prepare('UPDATE orders SET active=0,updated_at=? WHERE meal_id=? AND person_id=? AND active=1').bind(now(),meal.id,s.person_id).run();
  for(const item of chosen){const m=map.get(item.id);await env.DB.prepare('INSERT INTO orders(id,meal_id,event_id,person_id,meal_menu_id,name,price,qty,spice_level,note,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?)').bind(crypto.randomUUID(),meal.id,meal.event_id,s.person_id,m.id,m.name,m.price,Number(item.qty),String(item.spiceLevel||''),String(data.note||'').slice(0,200),now()).run()}
  await env.DB.prepare("INSERT INTO meal_people(meal_id,person_id,status,picked) VALUES(?,?,'已訂',0) ON CONFLICT(meal_id,person_id) DO UPDATE SET status='已訂',picked=0,picked_at=NULL").bind(meal.id,s.person_id).run();
  await log(env,s.name||s.person_id,'SAVE_ORDER','meal',meal.id,`共${chosen.reduce((a,x)=>a+Number(x.qty),0)}份`);
  return json({ok:true});
}
async function runBatch(env,statements,size=80){for(let i=0;i<statements.length;i+=size)await env.DB.batch(statements.slice(i,i+size))}
async function importLegacy(env,payload,actor){
  const src=payload?.kind==='meal-duty-diagnostic-backup'?payload.state:payload;
  if(!src||!Array.isArray(src.people)||!Array.isArray(src.events)||!Array.isArray(src.orders))throw new Error('不是有效的NAS診斷JSON');
  const people=[...(src.people||[])],stores=[...(src.stores||[])],events=[...(src.events||[])],meals=[...(src.meals||[])];
  const peopleIds=new Set(people.map(x=>x.id)),storeIds=new Set(stores.map(x=>x.id)),eventIds=new Set(events.map(x=>x.id)),mealIds=new Set(meals.map(x=>x.id));
  const addPerson=id=>{if(id&&!peopleIds.has(id)){peopleIds.add(id);people.push({id,name:`保留人員（${id}）`,group:'其他',active:false})}};
  const addStore=id=>{if(id&&!storeIds.has(id)){storeIds.add(id);stores.push({id,name:`保留店家（${id}）`,active:false})}};
  const addEvent=(id,date='2000-01-01')=>{if(id&&!eventIds.has(id)){eventIds.add(id);events.push({id,name:`保留活動（${id}）`,start:date,end:date,status:'已結束',active:false})}};
  const addMeal=(id,eventId,date='2000-01-01')=>{if(id&&!mealIds.has(id)){const eid=eventId||`legacy-event-${id}`;addEvent(eid,date);mealIds.add(id);meals.push({id,eventId:eid,date,type:'舊餐次',status:'停止登記',active:false})}};
  for(const x of src.menu||[])addStore(x.storeId);
  for(const x of src.mealMenus||[]){addMeal(x.mealId,null);addStore(x.storeId)}
  for(const x of meals){addEvent(x.eventId,x.date);addStore(x.storeId)}
  for(const x of src.orders||[]){addPerson(x.personId);addEvent(x.eventId);addMeal(x.mealId,x.eventId)}
  for(const x of src.mealPeople||[]){addPerson(x.personId);addMeal(x.mealId,null)}
  for(const x of src.payments||[]){addPerson(x.personId);addEvent(x.eventId)}
  let stage='準備匯入';
  try{
    stage='人員';await runBatch(env,people.map(p=>env.DB.prepare("INSERT INTO people(id,name,group_name,sort_order,active) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,group_name=excluded.group_name,sort_order=excluded.sort_order,active=excluded.active").bind(p.id,p.name,p.group||'其他',p.sort||0,p.active===false?0:1)));
    stage='店家';await runBatch(env,stores.map(s=>env.DB.prepare("INSERT INTO stores(id,name,phone,sort_order,active) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,phone=excluded.phone,sort_order=excluded.sort_order,active=excluded.active").bind(s.id,s.name,s.phone||'',s.sort||0,s.active===false?0:1)));
    stage='店家菜單';await runBatch(env,(src.menu||[]).map(x=>env.DB.prepare("INSERT INTO menu_items(id,store_id,name,price,spice_required,sort_order,active) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET store_id=excluded.store_id,name=excluded.name,price=excluded.price,spice_required=excluded.spice_required,sort_order=excluded.sort_order,active=excluded.active").bind(x.id,x.storeId,x.name,x.price||0,x.spiceRequired?1:0,x.sort||0,x.active===false?0:1)));
    stage='活動';await runBatch(env,events.map(e=>env.DB.prepare("INSERT INTO events(id,name,start_date,end_date,status,active) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,start_date=excluded.start_date,end_date=excluded.end_date,status=excluded.status,active=excluded.active").bind(e.id,e.name,e.start||'2000-01-01',e.end||e.start||'2000-01-01',e.status||'進行中',e.active===false?0:1)));
    stage='餐次';await runBatch(env,meals.map(m=>env.DB.prepare("INSERT INTO meals(id,event_id,meal_date,meal_type,store_id,status,active) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET event_id=excluded.event_id,meal_date=excluded.meal_date,meal_type=excluded.meal_type,store_id=excluded.store_id,status=excluded.status,active=excluded.active").bind(m.id,m.eventId,m.date||'2000-01-01',m.type||'舊餐次',m.storeId||null,m.status||'登記中',m.active===false?0:1)));
    stage='餐次菜單';await runBatch(env,(src.mealMenus||[]).map(x=>env.DB.prepare("INSERT INTO meal_menu_items(id,meal_id,source_id,store_id,name,price,spice_required,special,sort_order,active) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET meal_id=excluded.meal_id,source_id=excluded.source_id,store_id=excluded.store_id,name=excluded.name,price=excluded.price,spice_required=excluded.spice_required,special=excluded.special,sort_order=excluded.sort_order,active=excluded.active").bind(x.id,x.mealId,x.sourceId||null,x.storeId||null,x.name,x.price||0,x.spiceRequired?1:0,x.special?1:0,x.sort||0,x.active===false?0:1)));
    stage='訂單';await runBatch(env,(src.orders||[]).map(o=>env.DB.prepare("INSERT INTO orders(id,meal_id,event_id,person_id,meal_menu_id,name,price,qty,spice_level,note,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET meal_id=excluded.meal_id,event_id=excluded.event_id,person_id=excluded.person_id,meal_menu_id=excluded.meal_menu_id,name=excluded.name,price=excluded.price,qty=excluded.qty,spice_level=excluded.spice_level,note=excluded.note,active=excluded.active,updated_at=excluded.updated_at").bind(o.id,o.mealId,o.eventId,o.personId,o.mealMenuId,o.name,o.price||0,o.qty||1,o.spiceLevel||'',o.note||'',o.active===false?0:1,o.updatedAt||now())));
    stage='領餐狀態';await runBatch(env,(src.mealPeople||[]).map(x=>env.DB.prepare("INSERT INTO meal_people(meal_id,person_id,status,picked,picked_at) VALUES(?,?,?,?,?) ON CONFLICT(meal_id,person_id) DO UPDATE SET status=excluded.status,picked=excluded.picked,picked_at=excluded.picked_at").bind(x.mealId,x.personId,x.status||'已訂',x.picked?1:0,x.pickedAt||null)));
    stage='收費狀態';await runBatch(env,(src.payments||[]).map(x=>env.DB.prepare("INSERT INTO payments(event_id,person_id,paid,paid_at) VALUES(?,?,?,?) ON CONFLICT(event_id,person_id) DO UPDATE SET paid=excluded.paid,paid_at=excluded.paid_at").bind(x.eventId,x.personId,x.paid?1:0,x.paidAt||null)));
  }catch(error){throw new Error(`匯入「${stage}」時失敗：${error.message}`)}
  await log(env,actor,'IMPORT_LEGACY','system','',`${src.people.length}人｜${(src.stores||[]).length}店｜${src.events.length}活動｜${src.orders.length}訂單`);
  return{people:src.people.length,stores:(src.stores||[]).length,events:src.events.length,meals:(src.meals||[]).length,orders:src.orders.length};
}
export async function onRequest({request,env,params}){
  const segments=Array.isArray(params.path)?params.path:[params.path].filter(Boolean),path='/'+segments.join('/'),method=request.method;
  try{
    if(path==='/health')return json({ok:true,service:'meal-duty-cloudflare',version:'0.1.0'});
    if(path==='/public/bootstrap'&&method==='GET')return json({ok:true,...await publicBootstrap(env)});
    if(path==='/auth/person'&&method==='POST'){
      const d=await body(request),personId=String(d.personId||''),code=String(d.code||''),key=await pinAttemptKey(request,personId),attempt=await pinAttemptStatus(env,key),time=Date.now();
      if(Number(attempt?.lockedUntil||0)>time)return json({ok:false,message:`PIN 錯誤次數過多，請於 ${Math.max(1,Math.ceil((Number(attempt.lockedUntil)-time)/60000))} 分鐘後再試`},429);
      const person=await env.DB.prepare('SELECT * FROM people WHERE id=? AND active=1').bind(personId).first(),valid=/^\d{3}$/.test(code)&&person?.employee_code_hash===await digest(code);
      if(!valid){const lockedUntil=await recordPinFailure(env,key,attempt);return json({ok:false,message:lockedUntil?'PIN 錯誤次數過多，請於 10 分鐘後再試':'姓名或手機末三碼 PIN 不正確'},lockedUntil?429:401)}
      await env.DB.prepare('DELETE FROM pin_attempts WHERE attempt_key=?').bind(key).run();
      const admins=await adminPersonIds(env),role=admins.has(person.id)?'admin':'person',token=randomToken(),expires=Date.now()+30*24*3600*1000;await env.DB.prepare("INSERT INTO auth_sessions(token_hash,person_id,role,expires_at,code_version) VALUES(?,?,?,?,?)").bind(await digest(token),person.id,role,expires,person.code_version).run();await log(env,person.name,'LOGIN','person',person.id,'登入成功');return json({ok:true,token,person:{id:person.id,name:person.name,group:person.group_name,isAdmin:role==='admin'}});
    }
    if(path==='/auth/admin'&&method==='POST'){
      const d=await body(request),stored=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(!stored||stored.value!==await digest(String(d.password||'')))return json({ok:false,message:stored?'管理密碼不正確':'尚未設定管理密碼'},401);const token=randomToken();await env.DB.prepare("INSERT INTO auth_sessions(token_hash,role,expires_at) VALUES(?,'admin',?)").bind(await digest(token),Date.now()+8*3600*1000).run();return json({ok:true,token});
    }
    if(path==='/me'&&method==='GET'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);return json({ok:true,...await userBootstrap(env,s.person_id,s.role==='admin')});}
    if(path==='/orders'&&method==='POST'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);return saveOrder(env,s,await body(request));}
    if(path==='/overview'&&method==='GET'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);const mealId=new URL(request.url).searchParams.get('mealId'),meal=await env.DB.prepare("SELECT m.id,m.meal_date AS date,m.meal_type AS type,COALESCE(st.name,'尚未指定店家') AS storeName FROM meals m LEFT JOIN stores st ON st.id=m.store_id WHERE m.id=? AND m.active=1").bind(mealId).first();if(!meal)return json({ok:false,message:'找不到餐次'},404);const rows=await env.DB.prepare("SELECT p.id AS personId,p.name,p.group_name AS groupName,p.sort_order AS sortOrder,CASE WHEN o.spice_level='' THEN o.name ELSE o.name||'（'||o.spice_level||'）' END AS itemName,o.qty,COALESCE(mp.picked,0) AS picked FROM orders o JOIN people p ON p.id=o.person_id LEFT JOIN meal_people mp ON mp.meal_id=o.meal_id AND mp.person_id=o.person_id WHERE o.meal_id=? AND o.active=1 ORDER BY p.sort_order,p.name,o.name,o.spice_level").bind(mealId).all();const people=new Map(),items=new Map();for(const x of rows.results){if(!people.has(x.personId))people.set(x.personId,{id:x.personId,name:x.name,group:x.groupName,picked:!!x.picked,items:[]});people.get(x.personId).items.push({name:x.itemName,qty:x.qty});items.set(x.itemName,(items.get(x.itemName)||0)+Number(x.qty))}return json({ok:true,meal,canManage:s.role==='admin',people:[...people.values()],items:[...items].map(([name,qty])=>({name,qty})).sort((a,b)=>b.qty-a.qty||a.name.localeCompare(b.name,'zh-Hant'))});}
    if(path==='/payments'&&method==='GET'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請重新登入'},401);const events=await env.DB.prepare("SELECT MIN(e.id) AS id,e.name,e.start_date AS startDate,e.end_date AS endDate FROM events e JOIN orders o ON o.event_id=e.id AND o.active=1 WHERE e.active=1 GROUP BY TRIM(e.name),e.start_date,e.end_date ORDER BY e.start_date DESC").all(),requested=new URL(request.url).searchParams.get('eventId'),eventId=events.results.some(x=>x.id===requested)?requested:events.results[0]?.id;if(!eventId)return json({ok:true,events:events.results,people:[],canManage:s.role==='admin'});const totals=await env.DB.prepare("SELECT p.id,p.name,p.group_name AS 'group',p.sort_order AS sortOrder,SUM(o.price*o.qty) AS total,COALESCE(pay.paid,0) AS paid,pay.paid_at AS paidAt FROM orders o JOIN people p ON p.id=o.person_id JOIN events e ON e.id=o.event_id AND e.active=1 LEFT JOIN payments pay ON pay.event_id=o.event_id AND pay.person_id=o.person_id WHERE o.event_id=? AND o.active=1 GROUP BY p.id,p.name,p.group_name,p.sort_order,pay.paid,pay.paid_at ORDER BY p.sort_order,p.name").bind(eventId).all();const details=await env.DB.prepare("SELECT o.person_id AS personId,m.meal_date AS date,m.meal_type AS type,CASE WHEN o.spice_level='' THEN o.name ELSE o.name||'（'||o.spice_level||'）' END AS name,o.qty,o.price FROM orders o JOIN meals m ON m.id=o.meal_id JOIN events e ON e.id=o.event_id AND e.active=1 WHERE o.event_id=? AND o.active=1 ORDER BY o.person_id,m.meal_date,m.meal_type,o.name,o.spice_level").bind(eventId).all();return json({ok:true,eventId,events:events.results,people:totals.results,details:details.results,canManage:s.role==='admin'});}
    if(path==='/admin/claim'&&method==='POST'){const s=await session(env,request,'person');if(!s)return json({ok:false,message:'請先以人員帳號登入'},401);const ids=await adminPersonIds(env);if(ids.size&&!ids.has(s.person_id))return json({ok:false,message:'已有管理者，請由現有管理者授權'},409);const d=await body(request),stored=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(!stored||stored.value!==await digest(String(d.password||'')))return json({ok:false,message:'原管理密碼不正確'},401);ids.add(s.person_id);await saveAdminPersonIds(env,ids);await env.DB.prepare("UPDATE auth_sessions SET role='admin' WHERE token_hash=?").bind(await digest(bearer(request))).run();await log(env,s.name,'CLAIM_ADMIN','person',s.person_id,'綁定管理權限');return json({ok:true});}
    if(path==='/admin/permissions'&&method==='GET'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const ids=await adminPersonIds(env),people=await env.DB.prepare("SELECT id,name,group_name AS 'group',sort_order AS sortOrder FROM people WHERE active=1 ORDER BY sort_order,name").all();return json({ok:true,people:people.results.map(x=>({...x,isAdmin:ids.has(x.id)}))});}
    if(path==='/admin/permissions'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),personId=String(d.personId||''),enabled=d.enabled===true,person=await env.DB.prepare('SELECT id,name FROM people WHERE id=? AND active=1').bind(personId).first();if(!person)return json({ok:false,message:'找不到有效人員'},404);if(!enabled&&personId===String(s.person_id))return json({ok:false,message:'不能移除自己；請由另一位管理者操作'},409);const ids=await adminPersonIds(env);enabled?ids.add(personId):ids.delete(personId);if(!ids.size)return json({ok:false,message:'至少要保留一位管理者'},400);await saveAdminPersonIds(env,ids);await env.DB.prepare("UPDATE auth_sessions SET role=? WHERE person_id=?").bind(enabled?'admin':'person',personId).run();await log(env,s.name,'ADMIN_PERMISSION','person',personId,`${enabled?'授予':'移除'}｜${person.name}`);return json({ok:true,personId,enabled});}
    if(path==='/admin/pickup'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'需要管理權限'},401);const d=await body(request),ordered=await env.DB.prepare('SELECT 1 ok FROM orders WHERE meal_id=? AND person_id=? AND active=1 LIMIT 1').bind(d.mealId,d.personId).first();if(!ordered)return json({ok:false,message:'這位人員沒有本餐訂單'},404);await env.DB.prepare("INSERT INTO meal_people(meal_id,person_id,status,picked,picked_at) VALUES(?,?,'已訂',?,?) ON CONFLICT(meal_id,person_id) DO UPDATE SET picked=excluded.picked,picked_at=excluded.picked_at").bind(d.mealId,d.personId,d.picked?1:0,d.picked?now():null).run();await log(env,s.name,'PICKUP','meal',d.mealId,`${d.personId}|${d.picked?'已領':'取消'}`);return json({ok:true});}
    if(path==='/admin/payment'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'需要管理權限'},401);const d=await body(request),ordered=await env.DB.prepare('SELECT 1 ok FROM orders WHERE event_id=? AND person_id=? AND active=1 LIMIT 1').bind(d.eventId,d.personId).first();if(!ordered)return json({ok:false,message:'這位人員沒有本活動餐費'},404);await env.DB.prepare("INSERT INTO payments(event_id,person_id,paid,paid_at) VALUES(?,?,?,?) ON CONFLICT(event_id,person_id) DO UPDATE SET paid=excluded.paid,paid_at=excluded.paid_at").bind(d.eventId,d.personId,d.paid?1:0,d.paid?now():null).run();await log(env,s.name,'PAYMENT','event',d.eventId,`${d.personId}|${d.paid?'已收':'取消'}`);return json({ok:true});}
    if(path==='/admin/procurement'&&method==='GET'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const meals=await env.DB.prepare("SELECT m.id,m.event_id AS eventId,e.name AS eventName,m.meal_date AS date,m.meal_type AS type,m.status,COALESCE(s.name,'尚未指定店家') AS storeName,s.phone AS storePhone FROM meals m JOIN events e ON e.id=m.event_id LEFT JOIN stores s ON s.id=m.store_id WHERE m.active=1 AND e.active=1 ORDER BY m.meal_date DESC,CASE m.meal_type WHEN '晚餐' THEN 0 ELSE 1 END").all();const items=await env.DB.prepare("SELECT o.meal_id AS mealId,COALESCE(item_store.name,meal_store.name,'其他加購') AS storeName,CASE WHEN o.spice_level='' THEN o.name ELSE o.name||'（'||o.spice_level||'）' END AS name,SUM(o.qty) AS qty,SUM(o.price*o.qty) AS total FROM orders o JOIN meals m ON m.id=o.meal_id LEFT JOIN meal_menu_items mm ON mm.id=o.meal_menu_id LEFT JOIN stores item_store ON item_store.id=mm.store_id LEFT JOIN stores meal_store ON meal_store.id=m.store_id WHERE o.active=1 GROUP BY o.meal_id,COALESCE(item_store.name,meal_store.name,'其他加購'),o.name,o.spice_level ORDER BY o.meal_id,storeName,o.name,o.spice_level").all();return json({ok:true,meals:meals.results,items:items.results});}
    if(path==='/admin/bootstrap'&&method==='GET'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const counts={};for(const t of ['people','stores','events','meals','orders','logs'])counts[t]=(await env.DB.prepare(`SELECT COUNT(*) n FROM ${t}`).first()).n;const [people,stores,menu,events,meals]=await Promise.all([env.DB.prepare("SELECT id,name,group_name AS 'group',sort_order AS sortOrder,CASE WHEN employee_code_hash IS NULL THEN 0 ELSE 1 END AS hasCode FROM people WHERE active=1 ORDER BY sort_order,name").all(),env.DB.prepare("SELECT id,name,phone,sort_order AS sortOrder FROM stores WHERE active=1 ORDER BY sort_order,name").all(),env.DB.prepare("SELECT id,store_id AS storeId,name,price,spice_required AS spiceRequired,sort_order AS sortOrder FROM menu_items WHERE active=1 ORDER BY store_id,sort_order,name").all(),env.DB.prepare("SELECT id,name,start_date AS startDate,end_date AS endDate,status FROM events WHERE active=1 ORDER BY start_date DESC").all(),env.DB.prepare("SELECT m.id,m.event_id AS eventId,m.meal_date AS date,m.meal_type AS type,m.store_id AS storeId,m.status,COUNT(mm.id) AS menuCount FROM meals m LEFT JOIN meal_menu_items mm ON mm.meal_id=m.id AND mm.active=1 WHERE m.active=1 GROUP BY m.id ORDER BY m.meal_date,CASE m.meal_type WHEN '午餐' THEN 0 ELSE 1 END").all()]);return json({ok:true,counts,people:people.results,stores:stores.results,menu:menu.results,events:events.results,meals:meals.results});}
    if(path==='/admin/setup'&&method==='POST'){const existing=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(existing)return json({ok:false,message:'管理密碼已設定'},409);const d=await body(request);if(String(d.password||'').length<6)return json({ok:false,message:'管理密碼至少6碼'},400);await env.DB.prepare("INSERT INTO settings(key,value) VALUES('admin_password_hash',?)").bind(await digest(String(d.password))).run();return json({ok:true});}
    if(path==='/admin/password'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),current=String(d.currentPassword||''),next=String(d.newPassword||''),stored=await env.DB.prepare("SELECT value FROM settings WHERE key='admin_password_hash'").first();if(!stored||stored.value!==await digest(current))return json({ok:false,message:'目前管理密碼不正確'},401);if(next.length<6)return json({ok:false,message:'新密碼至少6碼'},400);await env.DB.prepare("UPDATE settings SET value=? WHERE key='admin_password_hash'").bind(await digest(next)).run();await log(env,s.name,'CHANGE_ADMIN_PASSWORD','settings','admin_password_hash','');return json({ok:true});}
    if(path==='/admin/import-legacy'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);return json({ok:true,summary:await importLegacy(env,await body(request),'管理者')});}
    if(path==='/admin/import-stores'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),incoming=Array.isArray(d.stores)?d.stores:[];if(!incoming.length)return json({ok:false,message:'檔案內沒有店家資料'},400);const [oldStores,oldMenu]=await Promise.all([env.DB.prepare('SELECT id,name FROM stores').all(),env.DB.prepare('SELECT id,store_id,name FROM menu_items').all()]),storeMap=new Map(oldStores.results.map(x=>[x.name.trim(),x])),menuMap=new Map(oldMenu.results.map(x=>[`${x.store_id}\n${x.name.trim()}`,x]));let storeCount=0,itemCount=0,sortStore=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0) n FROM stores').first()).n;const statements=[];for(const raw of incoming){const name=String(raw.name||'').trim(),phone=String(raw.phone||'').trim().slice(0,30);if(!name)continue;let store=storeMap.get(name);if(!store){store={id:crypto.randomUUID(),name};storeMap.set(name,store);statements.push(env.DB.prepare('INSERT INTO stores(id,name,phone,sort_order,active) VALUES(?,?,?,?,1)').bind(store.id,name,phone,++sortStore))}else statements.push(env.DB.prepare('UPDATE stores SET phone=?,active=1 WHERE id=?').bind(phone,store.id));storeCount++;let sortItem=0;for(const rawItem of(Array.isArray(raw.menu)?raw.menu:[])){const itemName=String(rawItem.name||'').trim();if(!itemName)continue;const price=Math.max(0,Math.round(Number(rawItem.price)||0)),spiceRequired=rawItem.spiceRequired===true?1:0,key=`${store.id}\n${itemName}`,old=menuMap.get(key);if(old)statements.push(env.DB.prepare('UPDATE menu_items SET price=?,spice_required=?,active=1 WHERE id=?').bind(price,spiceRequired,old.id));else statements.push(env.DB.prepare('INSERT INTO menu_items(id,store_id,name,price,spice_required,sort_order,active) VALUES(?,?,?,?,?,?,1)').bind(crypto.randomUUID(),store.id,itemName,price,spiceRequired,++sortItem));itemCount++}}await runBatch(env,statements);await log(env,'管理者','IMPORT_STORES','system','',`${storeCount}店｜${itemCount}項`);return json({ok:true,stores:storeCount,items:itemCount});}
    if(path==='/admin/person-code'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),code=String(d.code||'');if(!/^\d{3}$/.test(code))return json({ok:false,message:'PIN 必須是三位數'},400);await env.DB.prepare('UPDATE people SET employee_code_hash=?,code_version=code_version+1 WHERE id=?').bind(await digest(code),d.personId).run();await env.DB.prepare('DELETE FROM auth_sessions WHERE person_id=?').bind(d.personId).run();await log(env,s.name,'SET_PERSON_PIN','person',d.personId,'重設三碼 PIN');return json({ok:true});}
    if(path==='/admin/people'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),group=['師級','常日','輪班','其他'].includes(d.group)?d.group:'其他';if(!name)return json({ok:false,message:'請輸入姓名'},400);const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM people').first()).n;await env.DB.prepare('INSERT INTO people(id,name,group_name,sort_order,active) VALUES(?,?,?,?,1)').bind(id,name,group,sort).run();await log(env,'管理者','ADD_PERSON','person',id,`${name}｜${group}`);return json({ok:true,id});}
    if(path==='/admin/person-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),ids=await adminPersonIds(env);if(!d.active&&ids.has(d.id))return json({ok:false,message:'請先移除此人的管理權限，再停用人員'},409);await env.DB.prepare('UPDATE people SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();if(!d.active)await env.DB.prepare('DELETE FROM auth_sessions WHERE person_id=?').bind(d.id).run();await log(env,s.name,d.active?'RESTORE_PERSON':'DISABLE_PERSON','person',d.id,'');return json({ok:true});}
    if(path==='/admin/stores'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),phone=String(d.phone||'').trim().slice(0,30);if(!name)return json({ok:false,message:'請輸入店家名稱'},400);if(d.id){await env.DB.prepare('UPDATE stores SET name=?,phone=? WHERE id=?').bind(name,phone,d.id).run();await log(env,'管理者','UPDATE_STORE','store',d.id,`${name}｜${phone}`);return json({ok:true,id:d.id})}const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM stores').first()).n;await env.DB.prepare('INSERT INTO stores(id,name,phone,sort_order,active) VALUES(?,?,?,?,1)').bind(id,name,phone,sort).run();await log(env,'管理者','ADD_STORE','store',id,`${name}｜${phone}`);return json({ok:true,id});}
    if(path==='/admin/store-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request);await env.DB.prepare('UPDATE stores SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();await log(env,'管理者',d.active?'RESTORE_STORE':'DISABLE_STORE','store',d.id,'');return json({ok:true});}
    if(path==='/admin/menu-items'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),price=Math.max(0,Math.round(Number(d.price)||0)),spiceRequired=d.spiceRequired===true||d.spiceRequired==='on'?1:0;if(!name||!d.storeId)return json({ok:false,message:'店家與餐點名稱不可空白'},400);if(d.id){await env.DB.prepare('UPDATE menu_items SET name=?,price=?,spice_required=? WHERE id=? AND store_id=?').bind(name,price,spiceRequired,d.id,d.storeId).run();await log(env,'管理者','UPDATE_MENU','menu',d.id,`${name}｜${price}｜${spiceRequired?'辣度四選一':'無辣度'}`);return json({ok:true,id:d.id})}const id=crypto.randomUUID(),sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM menu_items WHERE store_id=?').bind(d.storeId).first()).n;await env.DB.prepare('INSERT INTO menu_items(id,store_id,name,price,spice_required,sort_order,active) VALUES(?,?,?,?,?,?,1)').bind(id,d.storeId,name,price,spiceRequired,sort).run();await log(env,'管理者','ADD_MENU','menu',id,`${name}｜${price}｜${spiceRequired?'辣度四選一':'無辣度'}`);return json({ok:true,id});}
    if(path==='/admin/menu-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request);await env.DB.prepare('UPDATE menu_items SET active=? WHERE id=?').bind(d.active?1:0,d.id).run();await log(env,'管理者',d.active?'RESTORE_MENU':'DISABLE_MENU','menu',d.id,'');return json({ok:true});}
    if(path==='/admin/events'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),start=String(d.startDate||''),end=String(d.endDate||''),startDate=new Date(`${start}T00:00:00Z`),endDate=new Date(`${end}T00:00:00Z`),days=Math.round((endDate-startDate)/86400000)+1,allowedTypes=['特餐','午餐','晚餐'],requestedTypes=Array.isArray(d.mealTypes)?d.mealTypes:['午餐','晚餐'],mealTypes=allowedTypes.filter(type=>requestedTypes.includes(type));if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||days<1||days>4)return json({ok:false,message:'請輸入活動名稱，日期需為1～4天'},400);if(!mealTypes.length)return json({ok:false,message:'請至少選擇一種餐次'},400);const eventId=crypto.randomUUID(),statements=[env.DB.prepare("INSERT INTO events(id,name,start_date,end_date,status,active) VALUES(?,?,?,?, '進行中',1)").bind(eventId,name,start,end)];for(let i=0;i<days;i++){const date=new Date(startDate.getTime()+i*86400000).toISOString().slice(0,10);for(const type of mealTypes)statements.push(env.DB.prepare("INSERT INTO meals(id,event_id,meal_date,meal_type,status,active) VALUES(?,?,?,?, '停止登記',1)").bind(crypto.randomUUID(),eventId,date,type))}await env.DB.batch(statements);await log(env,'管理者','ADD_EVENT','event',eventId,`${name}｜${start}～${end}｜${mealTypes.join('、')}`);return json({ok:true,id:eventId,meals:days*mealTypes.length});}
    if(path==='/admin/event-active'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),id=String(d.id||'');if(!id)return json({ok:false,message:'缺少活動編號'},400);const active=d.active===true?1:0;await env.DB.prepare('UPDATE events SET active=? WHERE id=?').bind(active,id).run();await log(env,s.name,'SET_EVENT_ACTIVE','event',id,String(active));return json({ok:true,id,active:!!active});}
    if(path==='/admin/meal-status'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),status=d.status==='登記中'?'登記中':'停止登記';await env.DB.prepare('UPDATE meals SET status=? WHERE id=? AND active=1').bind(status,d.mealId).run();await log(env,'管理者','MEAL_STATUS','meal',d.mealId,status);return json({ok:true,status});}
    if(path==='/admin/meal-store'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),meal=await env.DB.prepare('SELECT id FROM meals WHERE id=? AND active=1').bind(d.mealId).first(),store=await env.DB.prepare('SELECT id,name FROM stores WHERE id=? AND active=1').bind(d.storeId).first();if(!meal||!store)return json({ok:false,message:'找不到餐次或店家'},404);const source=await env.DB.prepare('SELECT id,name,price,spice_required AS spiceRequired,sort_order FROM menu_items WHERE store_id=? AND active=1 ORDER BY sort_order,name').bind(store.id).all();if(!source.results.length)return json({ok:false,message:'這家店尚無可用菜單'},400);if(d.mode!=='append')await env.DB.prepare('UPDATE meal_menu_items SET active=0 WHERE meal_id=?').bind(meal.id).run();await env.DB.prepare('UPDATE meals SET store_id=? WHERE id=?').bind(store.id,meal.id).run();const statements=source.results.map(x=>env.DB.prepare('INSERT INTO meal_menu_items(id,meal_id,source_id,store_id,name,price,spice_required,special,sort_order,active) VALUES(?,?,?,?,?,?,?,0,?,1)').bind(crypto.randomUUID(),meal.id,x.id,store.id,x.name,x.price,x.spiceRequired,x.sort_order));await runBatch(env,statements);await log(env,'管理者',d.mode==='append'?'APPEND_MEAL_STORE':'REPLACE_MEAL_STORE','meal',meal.id,store.name);return json({ok:true,items:source.results.length});}
    if(path==='/admin/meal-special'&&method==='POST'){const s=await session(env,request,'admin');if(!s)return json({ok:false,message:'管理權限已失效'},401);const d=await body(request),name=String(d.name||'').trim(),price=Math.max(0,Math.round(Number(d.price)||0));if(!name||!d.mealId)return json({ok:false,message:'請輸入品項與價格'},400);const sort=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM meal_menu_items WHERE meal_id=?').bind(d.mealId).first()).n,id=crypto.randomUUID();await env.DB.prepare('INSERT INTO meal_menu_items(id,meal_id,name,price,special,sort_order,active) VALUES(?,?,?,?,1,?,1)').bind(id,d.mealId,name,price,sort).run();await log(env,'管理者','ADD_MEAL_SPECIAL','meal',d.mealId,`${name}｜${price}`);return json({ok:true,id});}
    return json({ok:false,message:'找不到API'},404);
  }catch(error){return json({ok:false,message:error.message||'伺服器錯誤'},500)}
}
